### ISSUE TITLE
Volunteer moderator

### ISSUE THREAD

**Issue by weqaar** [Zabiplane/Community#1]
Hi,

In response to Vicky's post, I volunteer to be an additional moderator for this list, in UTC timezone.

Thanks,
Weqaar

**Comment by vmbrasseur** [comment]
Thank you, @weqaar! I've flipped the moderator bit so you should be good to go. Please don't forget to review the doc about group moderation: https://github.com/Zabiplane/Community/blob/master/communityadmin/groupsiomoderating.md

Welcome to the moderators!
