### ISSUE TITLE
Request for contributor access

### ISSUE THREAD

**Issue by weqaar** [Zabiplane/Community#2]
Hi,

This is to request contributor access rights to this repo so we may submit PRs.

Thanks,
Weqaar

**Comment by vmbrasseur** [comment]
You should be able to submit PRs by cloning the repo and submitting just a usual…? Is that not working for you?

For now I'm not giving commit bits to others for this repo because I want the dust to settle around the community organisation before I start handing out keys to the kingdom.

**Comment by weqaar** [comment]
Understandable, we do not have much at this stage anyway, just few minor fixes to what we have so far - url fixes.

Usual is not working, unable to push local branch to upstream for PR:

> git push -u origin weqaar-dev
> ERROR: Permission to Zabiplane/Community.git denied to weqaar.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

**Comment by vmbrasseur** [comment]
That usual assumes you have a commit bit. It's a git push, not a pull request. Please try a standard GitHub pull request instead.

**Comment by weqaar** [comment]
Certainly :) since that is assumed, I didn't bother pasting those bits up there:

> git add README.md 
> git commit -S -m "fix broken links in working groups section"

**Comment by vmbrasseur** [comment]
Commit bit isn't required to send a PR, but GitHub is. You can use git-request-pull to create a pull request at the command line…but it's not compatible with GitHub's style of pull request. So the GitHub UI is required for pull requests, as far as I know. [Instructions here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request).

**Comment by weqaar** [comment]
Creating a branch is required for PRs as PR between master<->master does not make sense, from the URL you referred to: 

> Pull requests can only be opened between two branches that are different.

Thus, if we don't have access to create branches, there isn't any way to create a PR without **forking** this repo - which is something I do not intend to do.

Need **collaborator** rights to create branch and PR. 

If that is not an option at this point in time, due to the reason - repeating your statement here:

> I want the dust to settle around the community organisation 

I suggest you could then make this change to README (refer to diff ^^), thanks.

**Comment by vmbrasseur** [comment]
Please fork the repo if you would like to send PRs. This is standard operating procedure for projects that are hosted on GitHub.
