### ISSUE TITLE
Slack workspace

### ISSUE THREAD

**Issue by weqaar** [Zabiplane/Community#4]
Hi,

Slack workspace [zabiplane.slack.com](https://zabiplane.slack.com/) is available if we agree on using it, if not this can be removed, great if we could integrate with Github.

https://zabiplane.slack.com/signup

Thanks,
Weqaar

**Comment by vmbrasseur** [comment]
I appreciate that you're trying to help, but no, we will not be using Slack.

The community already decided at the first f2f meeting that it will not be using Slack. Not only is it a closed service, it's also not available in China and therefore is not inclusive of many of our potential contributors.

We also decided that a real time chat system is not an MVP for the community at this stage. If the community decides later—together, after discussion—that one is needed, then we'll cross that bridge. For now we'll be using email.

@weqaar, could you please transfer ownership of that slack to me? Please use my Juniper email address for that. Let me know if I need to join the Slack before you can do so.

**Comment by vmbrasseur** [comment]
After transferring the Slack to me, I encourage you to revisit the report of the first f2f meeting: https://docs.google.com/document/d/1I7Qo_eQdntJWyVqbm7WlIK8-c0yWHmxUDd2TJnm00KQ/edit#heading=h.akmokdlo17on

**Comment by weqaar** [comment]
Acknowledged, once you join I will change you to Owner.

**Comment by vmbrasseur** [comment]
Joined! :)

**Comment by weqaar** [comment]
You are now the Primary and Full owner now, missed the note there, appreciate the reference.

**Comment by vmbrasseur** [comment]
Thank you!
